### ISSUE TITLE
Need ability to specify target resource group during schematics:deploy job

### ISSUE THREAD

**Issue by jpapejr** [IBM-Cloud/vscode-ibmcloud-schematics#19]
**Is your feature request related to a problem? Please describe.**
In a large shared account, we have to constrain ourselves by only provisioning resources in our own resource group. Deploying a new workspace via this tool results in `default` always being the target resource group. 

**Describe the solution you'd like**
Either prompt to the desired target resource group, or allow the user to indicate it in a configuration file or extension preference. 

**Describe alternatives you've considered**
Pre-creating the workspace in the target RG and then trying to clone the existing repo feel clunky: I end up with another directory with contents or an error about not being able clone the code (something about a redirect URL or something like that)

**Additional context**
N/A

**Comment by VishwaKumar** [comment]
This feature has been rolled out in newer version [v1.3.0](https://github.com/IBM-Cloud/vscode-ibmcloud-schematics/releases/tag/v1.3.0)
Please update to this latest version from extension marketplace.
